### ISSUE TITLE
No secret key was set

### ISSUE THREAD

**Issue by prd001** [CESNET/exafs#2]
Hi,

after installing the exafs, my apache server gives me error 500 and in the flowspec log file, there is the message: 
```
[pid: 55079|app: 0|req: 6/6] 10.0.131.28 (p*******1) {122 vars in 2110 bytes} [Wed Mar 27 14:15:46 2019] GET / => generated 0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/deploy/www/venv/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/deploy/www/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/deploy/www/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/deploy/www/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/deploy/www/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/deploy/www/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/deploy/www/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/deploy/www/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flowapp/auth.py", line 16, in decorated
    if not check_auth(get_user()):
  File "./flowapp/auth.py", line 85, in check_auth
    session['app_version'] = __version__
  File "/home/deploy/www/venv/lib/python2.7/site-packages/werkzeug/local.py", line 351, in __setitem__
    self._get_current_object()[key] = value
  File "/home/deploy/www/venv/lib/python2.7/site-packages/flask/sessions.py", line 101, in _fail
    raise RuntimeError('The session is unavailable because no secret '
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
```

I am running LDAP authentication instead of ShibbolethSP though. Is the secret key generated somewhere or is it just missing from some config file?

Thanks

**Comment by jirivrany** [comment]
Thanks for pointing this out. Secret key should be set in the config.py - see updated config example.
